name: Deploy Lambda File Processor
on:
  push:
    branches: [ dev ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        working-directory: Terraform
        run: terraform init
      - name: Terraform Apply
        working-directory: Terraform
        run: terraform apply -auto-approve
      - name: Get Terraform outputs and export as env vars
        working-directory: Terraform
        run: |
          BUCKET_NAME=$(terraform output -raw s3_bucket_name | tr -d '\n\r')
          API_ENDPOINT=$(terraform output -raw api_endpoint | tr -d '\n\r')
          echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV
          echo "API_ENDPOINT=$API_ENDPOINT" >> $GITHUB_ENV
      - name: Debug outputs
        run: |
          echo "S3 Bucket: $BUCKET_NAME"
          echo "API Endpoint: $API_ENDPOINT"
      - name: Upload test file to S3
        run: |
          echo "Hello from GitHub Actions" > testfile.txt
          aws s3 cp testfile.txt s3://$BUCKET_NAME/testfile.txt
      - name: Test Lambda via API Gateway
        run: |
          curl -X POST $API_ENDPOINT/process \
            -H "Content-Type: application/json" \
            -d '{"test":"data"}'
      - name: Print resource information
        run: |
          echo "S3 Bucket: $BUCKET_NAME"
          echo "API Endpoint: $API_ENDPOINT"